---
# tasks file for Apache
 - include_vars: "{{ ansible_os_family }}.yml"

 - include: Install_RedHat.yml
   when: ansible_distribution == "RedHat"

 - include: Install_Ubuntu.yml
   when: ansible_distribution == "Ubuntu"

 - include: copy_RedHat.yml
   when: ansible_distribution == "RedHat"

 - include: copy_Ubuntu.yml
   when: ansible_distribution == "Ubuntu"

 - name: restrt the apachen service
   service: name={{ package_redhat }} state=restarted   
